#!/usr/bin/env python3
# Shared engine for validating a RimWorld mod's translation files against its
# English source of truth and its checked-in expectations sidecar. Consumed
# by each mod repo via a thin Scripts/check-translations.py shim that
# sys.path-inserts this file's directory, imports it, assigns the config
# variables below by module attribute (e.g. `engine.REQUIRED_DLCS = {...}`),
# and calls main(). Deterministic companion to the translate skill/workflow:
# anything this script can prove is never re-derived by an agent.
#
# Config variables a shim MUST set before calling main() (see each variable's
# own comment below for details):
#   PARITY_EXEMPT_FIELDS  set[str]        fields exempt from cross-language parity
#   REQUIRED_DLCS         set[str]        DLCs the sidecar must be generated with
#   DEF_TYPE_ALIASES      dict[str, str]  subclass element tag -> dumped def type
#   ALLOW_NO_KEYED_SURFACE bool           tolerate a mod with no Languages/Keyed tree
#
# The DefInjected expected set comes from Scripts/expected-injections.json —
# a dump of every legal injection point the LIVE game sees for this mod,
# generated by refresh_expectations.py (this engine's refresh half) driving
# the L10nProbe dev mod (which calls the game's own walker,
# Verse.DefInjectionUtility.ForEachPossibleDefInjection). That is the only
# way to see translatable text this script's def-XML scan structurally
# cannot: fields inherited from VANILLA parents (melee tools lists,
# FactionBase's messageDefendersAttacking, InjuryBase's labelNounPretty) and
# C# field DEFAULTS never written in any XML (the ability comp's chargeNoun /
# cooldownGerund). Unknown gap classes are impossible by structure: any
# defName in Defs/ the sidecar has never seen fails this script until the
# sidecar is regenerated, and the regen sees everything the game sees.
#
# Checks per non-English language:
#   Keyed:       missing/extra keys, argument-placeholder mismatches, stale EN
#                comments (grammar constructs like {PAWN_gender ? a : b : c} are
#                language-specific and deliberately not compared - see below)
#   DefInjected: folder names are sidecar def types, every key is a legal
#                injection point (directly, via the sidecar's normalized
#                alias, or as element N of a collection entry), placeholder
#                and stale-EN-comment checks against the sidecar's English,
#                completeness of the sidecar's required subset
#   All files:   well-formed XML, <LanguageData> root, UTF-8 no BOM, LF line
#                endings, no tabs, final newline (hygiene -> warnings)
# Plus, language-independent:
#   Sidecar:     generated with the right DLC set (MayRequire-gated defs
#                vanish from a dump made without their DLC), fresh against
#                Defs/ (defNames and label/description English text)
#
# Staleness relies on the EN-comment convention: every translated entry carries
# the English source directly above it, e.g.
#   <!-- EN: Reset to defaults -->
#   <Prefix_ResetToDefaults>...</Prefix_ResetToDefaults>
# A missing EN comment is a warning; an EN comment that no longer matches the
# current English text is an error (the translation is stale).
#
# Exit code: 1 if any errors (or, with --strict, any warnings), else 0.

import argparse
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

PLACEHOLDER_RE = re.compile(r"\{[^{}]*\}")
EN_COMMENT_RE = re.compile(r"^\s*EN:\s?(.*)$", re.DOTALL)

# A {...} span is one of two different things, and only one of them is an interface
# contract with the C# call site.
#
#   argument placeholder   {0}, {1}, {PAWN_labelShort}
#       Supplied by the caller. A language that drops or invents one is broken, so
#       these must match English exactly.
#
#   grammar construct      {PAWN_gender ? é : ée : é(e)}, {0_gender ? un : une : un(e)}
#       Resolved by GrammarResolverSimple from an argument's gender, and inflecting
#       languages need them where uninflected English does not. French Core writes
#       Cut.deathMessage as "{0} a été taillad{PAWN_gender ? é : ée : é(e)} à mort."
#       against an English "{0} has been cut to death." (HealthUtility passes both
#       pawn.LabelShortCap and pawn.Named("PAWN") precisely so this resolves.)
#       Comparing these across languages would forbid correct translations.
#
# So grammar constructs are excluded before comparing. This does not weaken the
# argument check: a construct references its subject as "PAWN_gender", never as a
# bare "{0}", so a translation that dropped a real argument still fails.
GRAMMAR_CONSTRUCT_RE = re.compile(r"\{[^{}]*\?[^{}]*\}")

# ...with one exception, and it is the reason this is not a plain exclusion.
# _numCase is the only ?-construct that CONSUMES AND PRINTS its argument
# (decompile-verified, Verse.LanguageWorker.ResolveNumCase: it returns
# `number + " " + form`, where every other construct returns only a form).
# Numeral-agreement languages therefore replace the bare placeholder with it
# rather than writing both: Core ru renders "{0} days" as
# "{0_numCase ? день : дня : дней}" — writing "{0} {0_numCase ...}" would
# print the number twice. Rewriting it back to its bare placeholder before
# the comparison keeps the argument contract enforced (drop argument 0
# entirely and it still fails) without forbidding the correct Russian.
NUM_CASE_RE = re.compile(r"\{([^{}?]*?)_numCase\s*\?[^{}]*\}")

# Fields whose entries legitimately vary per language (RimWorld's
# [TranslationCanChangeCount]-style matching tokens, e.g. one repo's
# labelKeywords): exempt from the cross-language parity check, keyed on the
# final path segment. Neutral default; the consuming repo's
# Scripts/check-translations.py shim assigns the real value after import
# (module attribute assignment, e.g. `engine.PARITY_EXEMPT_FIELDS = {...}`).
# The sidecar's fullListAllowed flag could eventually subsume this.
PARITY_EXEMPT_FIELDS = set()

# DLCs the sidecar must have been generated with. None is not a legitimate
# configured value (an empty set is: "this mod requires no DLC") — it means
# the shim forgot to configure this engine, so load_sidecar() below fails
# loudly at startup rather than silently skipping the DLC-freshness check.
# The consuming repo's shim assigns the real value after import.
REQUIRED_DLCS = None

# Def XML may declare a def via a subclass the game rolls into a base-type
# database — the probe's walker (the game's own) then dumps those defs under
# the base type, and DefInjected translations legally target that base-type
# folder. Map each subclass element tag seen in this repo's Defs/ to the def
# type the dump actually uses. Neutral default; the consuming repo's shim
# assigns the real value after import.
DEF_TYPE_ALIASES = {}

# When True, reproduce BionicThumbGuild's behavior: a mod with no shipped
# Languages/ tree, or no English Keyed strings, is a legal state (its
# translatable surface is DefInjected-only), not a config error — main()
# prints an informational note and continues rather than exiting with an
# error. When False (the default, matching every repo but BionicThumbGuild),
# either condition is a hard failure (stderr + exit 2).
ALLOW_NO_KEYED_SURFACE = False

# The consuming repo's root. Shims set this from their own file location
# (Path(__file__).resolve().parent.parent), which keeps the historical
# behavior of working from any cwd; left None, --root falls back to the
# current working directory.
REPO_ROOT = None


def norm(text):
    # The game decodes literal "\n" escapes in def XML text at load, so the
    # sidecar (dumped game-side) holds real newlines where the XML holds two
    # characters; decode before collapsing whitespace or every multi-paragraph
    # description reads as drifted.
    return re.sub(r"\s+", " ", (text or "").replace("\\n", "\n").strip())


def placeholders(text):
    text = NUM_CASE_RE.sub(r"{\1}", text or "")
    return set(PLACEHOLDER_RE.findall(GRAMMAR_CONSTRUCT_RE.sub("", text)))


def parse_with_comments(path):
    # Returns (root, entries) where entries is [(key, text, en_comment)].
    # The EN comment for an entry is the nearest preceding EN: comment that
    # appears after the previous element (section headers are skipped).
    builder = ET.TreeBuilder(insert_comments=True)
    root = ET.parse(path, parser=ET.XMLParser(target=builder)).getroot()
    entries = []
    pending_en = None
    for node in root:
        if node.tag is ET.Comment:
            m = EN_COMMENT_RE.match(node.text or "")
            if m:
                pending_en = m.group(1)
        else:
            entries.append((node.tag, node, pending_en))
            pending_en = None
    return root, entries


def flatten_entry(elem):
    # A Keyed/DefInjected entry is either a single text value or a list of <li>.
    kids = list(elem)
    if kids:
        return [li.text or "" for li in kids]
    return elem.text or ""


class Report:
    def __init__(self):
        self.errors = []
        self.warnings = []

    def error(self, path, msg):
        self.errors.append(f"{path}: {msg}")

    def warn(self, path, msg):
        self.warnings.append(f"{path}: {msg}")


def check_hygiene(path, report):
    raw = path.read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        report.error(path, "UTF-8 BOM present")
    if b"\r" in raw:
        report.warn(path, "CRLF line endings (repo convention is LF)")
    if b"\t" in raw:
        report.warn(path, "tab indentation (repo convention is 2 spaces)")
    if raw and not raw.endswith(b"\n"):
        report.warn(path, "missing final newline")


def load_language_xml(path, report):
    check_hygiene(path, report)
    try:
        root, entries = parse_with_comments(path)
    except ET.ParseError as e:
        report.error(path, f"XML parse error: {e}")
        return None
    if root.tag != "LanguageData":
        report.error(path, f"root element is <{root.tag}>, expected <LanguageData>")
        return None
    return entries


def collect_keyed(lang_dirs, report):
    # key -> (text, en_comment, path). Takes every root a language occupies (the
    # main 1.6/Languages/<Lang> plus any LoadFolders-gated compat root under
    # 1.6/Mods/<Mod Name>/Languages/<Lang>); the game merges them into one
    # LoadedLanguage, so duplicate keys collide across roots too.
    keyed = {}
    for lang_dir in lang_dirs:
        keyed_dir = lang_dir / "Keyed"
        for path in sorted(keyed_dir.glob("**/*.xml")) if keyed_dir.is_dir() else []:
            entries = load_language_xml(path, report)
            for key, elem, en in entries or []:
                if key in keyed:
                    report.error(path, f"duplicate key <{key}> (also in {keyed[key][2]})")
                keyed[key] = (flatten_entry(elem), en, path)
    return keyed


def def_is_active(elem, active_packages):
    # A def whose root node is MayRequire-gated on a package that was not
    # active during the probe boot never loaded there, so it is legitimately
    # absent from the sidecar and outside the l10n surface (e.g.
    # BetterTradersGuild's Biotech-gated ScenPartDef, where this fix
    # originated). MayRequire = ALL listed packages must be active;
    # MayRequireAnyOf = any.
    may_require = elem.get("MayRequire")
    if may_require:
        ids = {p.strip().lower() for p in may_require.split(",") if p.strip()}
        if not ids <= active_packages:
            return False
    any_of = elem.get("MayRequireAnyOf")
    if any_of:
        ids = {p.strip().lower() for p in any_of.split(",") if p.strip()}
        if ids and not ids & active_packages:
            return False
    return True


def collect_defs(defs_dirs, active_packages):
    # Returns (defs, def_roots): defs is tag -> {defName -> element};
    # def_roots is tag -> {defName -> load root that declares the def} (the
    # dir holding its Defs/, i.e. the main version folder or a gated compat
    # root). A def's DefInjected entries must ship from the SAME load root —
    # the game gates entries by the folder that contains them, not by the
    # def they target — so def_roots is what lets the language checks catch
    # wrong-root placement. Abstract parents (Name=, no defName) are not
    # collected: they are not injection targets themselves. Defs gated on
    # packages inactive during the probe boot are skipped (see def_is_active).
    defs = {}
    def_roots = {}
    for defs_dir in defs_dirs:
        load_root = defs_dir.parent
        for path in sorted(defs_dir.glob("**/*.xml")):
            try:
                root = ET.parse(path).getroot()
            except ET.ParseError:
                continue
            if root.tag != "Defs":
                continue
            for elem in root:
                if elem.tag is ET.Comment:
                    continue
                def_name = elem.findtext("defName")
                if def_name and def_is_active(elem, active_packages):
                    def_type = DEF_TYPE_ALIASES.get(elem.tag, elem.tag)
                    defs.setdefault(def_type, {})[def_name] = elem
                    def_roots.setdefault(def_type, {})[def_name] = load_root
    return defs, def_roots


def check_entry_root(def_roots, def_type, canonical, entry_root, path, report):
    # An injection entry loads (or not) with the load root that CONTAINS it —
    # the game never looks at which root declares the def it targets. So an
    # entry for a gated def placed in the main tree loads unconditionally and
    # is a found-no-def startup error whenever the gate is inactive, and an
    # entry for a main-tree def placed in a compat root silently vanishes
    # whenever the gate IS inactive. Both directions reduce to one rule:
    # entries live in the same load root as their def. Defs the local scan
    # never saw (nothing in this repo's Defs/) can't be checked and pass.
    owner = def_roots.get(def_type, {}).get(canonical.split(".")[0])
    if owner is not None and owner != entry_root:
        report.error(path, f"<{canonical.split('.')[0]}> is declared under "
                           f"{owner}, so its injections must live under "
                           f"{owner / 'Languages'} — entries gate by the "
                           f"folder that contains them, not by their def")
        return False
    return True


class Sidecar:
    # Scripts/expected-injections.json, indexed for lookups. Every entry is a
    # legal injection point; entries with required=true are what the in-game
    # report would list as missing and form the per-language completeness
    # demand. Keys are suggestedPath (handle form); an entry carries
    # "normalized" (index form) when it differs, and translation files may
    # use either — the game dedups by normalizedPath. A collection is ONE
    # entry at its path carrying all English elements; languages may
    # translate it as a full <li> list at that path or element-wise at
    # path.N.
    def __init__(self, data):
        self.meta = data.get("meta", {})
        self.entries = data["defInjections"]  # def_type -> key -> entry
        self.canon = {}       # def_type -> spelling -> canonical key
        self.def_names = {}   # def_type -> set of defNames seen
        for dt, entries in self.entries.items():
            spell = self.canon.setdefault(dt, {})
            names = self.def_names.setdefault(dt, set())
            for key, entry in entries.items():
                spell[key] = key
                if "normalized" in entry:
                    spell[entry["normalized"]] = key
                names.add(key.split(".")[0])

    @property
    def def_types(self):
        return set(self.entries)

    @property
    def active_packages(self):
        # Lowercased packageIds active during the probe boot: Core plus each
        # active DLC (ludeon.rimworld.<dlc>), plus meta.activeMods when the
        # refresh script recorded it (older sidecars predate that field).
        pkgs = {"ludeon.rimworld"}
        for dlc in self.meta.get("activeDlcs", []):
            if dlc != "Core":
                pkgs.add(f"ludeon.rimworld.{dlc.lower()}")
        pkgs.update(m.lower() for m in self.meta.get("activeMods", []))
        return pkgs

    def lookup(self, def_type, key):
        # Resolve a translated key to (canonical_key, element_index):
        # element_index is None for the entry itself (scalar, or a full-list
        # translation of a collection), an int for a path.N element of a
        # collection. Returns None for keys that are not legal injection
        # points.
        spell = self.canon.get(def_type, {})
        if key in spell:
            return spell[key], None
        head, _, tail = key.rpartition(".")
        if tail.isdigit() and head in spell:
            canonical = spell[head]
            entry = self.entries[def_type][canonical]
            if entry.get("isCollection") and int(tail) < len(entry["english"]):
                return canonical, int(tail)
        return None

    def required(self, def_type):
        return {k: e for k, e in self.entries.get(def_type, {}).items()
                if e.get("required")}


def load_sidecar(root, report):
    path = root / "Scripts" / "expected-injections.json"
    if not path.is_file():
        print(f"{path} is missing — generate it with "
              f"Scripts/refresh-translation-expectations.py", file=sys.stderr)
        return None
    sidecar = Sidecar(json.loads(path.read_text(encoding="utf-8")))
    missing_dlcs = REQUIRED_DLCS - set(sidecar.meta.get("activeDlcs", []))
    if missing_dlcs:
        report.error(path, f"sidecar was generated without "
                           f"{sorted(missing_dlcs)} active — MayRequire-gated "
                           f"defs are absent from it; rerun the probe with "
                           f"the right DLC set")
    return sidecar


def check_sidecar_freshness(defs, sidecar, report):
    # The rule that makes stale expectations loud: every def carrying a
    # label/description in XML must appear in the sidecar, so new or edited
    # translatable content forces a regen, and the regen sees everything the
    # game sees. The probe dumps only defs with at least one possible
    # injection point, so defs with NO translatable text in XML (most
    # DutyDefs, PrefabDefs, ...) are legitimately absent and tolerated —
    # whether or not their def type has other entries.
    label = "[Scripts/expected-injections.json]"
    stale = (f"expectations stale — rerun "
             f"Scripts/refresh-translation-expectations.py")
    for def_type, by_name in sorted(defs.items()):
        if def_type not in sidecar.def_types:
            for def_name, elem in sorted(by_name.items()):
                if elem.find("label") is not None \
                        or elem.find("description") is not None:
                    report.error(label, f"{def_type} {def_name} has a label/"
                                        f"description but its def type has no "
                                        f"sidecar entries; {stale}")
            continue
        # English drift: a label/description added or edited in XML without a
        # regen. (Literal-\n unescaping lives in norm().)
        for def_name, elem in sorted(by_name.items()):
            for field in ("label", "description"):
                node = elem.find(field)
                if node is None:
                    continue
                entry = sidecar.entries[def_type].get(f"{def_name}.{field}")
                if entry is None:
                    report.error(label, f"{def_type} {def_name}.{field} is in "
                                        f"the def XML but not the sidecar; "
                                        f"{stale}")
                elif norm(entry["english"]) != norm(node.text):
                    report.error(label, f"{def_type} {def_name}.{field} "
                                        f"English differs between def XML and "
                                        f"sidecar; {stale}")


def check_english_definjected(lang_dir, sidecar, def_roots, seen, report):
    # English DefInjected files inject into defs at runtime exactly like any
    # other language's, so an unknown key here is a live "found no def named
    # ..." startup error, not just translator noise — historically these files
    # were only read as reference material and never validated themselves.
    # Every entry must be a legal injection point per the sidecar, its text
    # must match the sidecar's English (drift means the file or the def was
    # edited without a regen), and a key may only be injected once across all
    # English roots (the game dedups by normalizedPath and warns). `seen` is
    # shared across roots: def_type -> key -> first path.
    inj_dir = lang_dir / "DefInjected"
    if not inj_dir.is_dir():
        return
    for type_dir in sorted(p for p in inj_dir.iterdir() if p.is_dir()):
        def_type = type_dir.name
        if def_type not in sidecar.def_types:
            report.error(f"[English/DefInjected/{def_type}]",
                         f"unknown def type folder (no legal injection "
                         f"points in the sidecar)")
            continue
        for path in sorted(type_dir.glob("**/*.xml")):
            for key, elem, _ in load_language_xml(path, report) or []:
                by_key = seen.setdefault(def_type, {})
                if key in by_key:
                    report.error(path, f"duplicate key <{key}> (also in "
                                       f"{by_key[key]})")
                    continue
                by_key[key] = path
                hit = sidecar.lookup(def_type, key)
                if hit is None:
                    report.error(path, f"unknown key <{key}> (not a legal "
                                       f"injection point per the sidecar)")
                    continue
                canonical, idx = hit
                check_entry_root(def_roots, def_type, canonical,
                                 lang_dir.parent.parent, path, report)
                entry = sidecar.entries[def_type][canonical]
                text = flatten_entry(elem)
                if idx is not None:
                    expected = entry["english"][idx]
                elif entry.get("isCollection"):
                    if not isinstance(text, list):
                        report.error(path, f"<{key}> is a collection entry; "
                                           f"expected a <li> list or "
                                           f"element-wise {key}.N keys")
                        continue
                    if len(text) != len(entry["english"]):
                        report.error(path, f"<{key}> has {len(text)} "
                                           f"elements, sidecar English has "
                                           f"{len(entry['english'])}")
                        continue
                    for i, (got, exp) in enumerate(zip(text, entry["english"])):
                        if norm(got) != norm(exp):
                            report.error(path, f"<{key}.{i}> drifted from "
                                               f"sidecar English {exp!r} — "
                                               f"rerun the refresh script or "
                                               f"fix the entry")
                    continue
                else:
                    expected = entry["english"]
                if isinstance(text, list):
                    report.error(path, f"<{key}> is scalar per the sidecar "
                                       f"but holds a <li> list")
                elif norm(text) != norm(expected):
                    report.error(path, f"<{key}> drifted from sidecar "
                                       f"English {expected!r} — rerun the "
                                       f"refresh script or fix the entry")


def check_language(lang_dirs, english_keyed, sidecar, def_roots, report):
    # Returns {def_type: set(canonical keys/elements)} actually translated in
    # this language, for the cross-language parity check in main(). Element
    # translations are recorded as "<canonical collection key>.<index>".
    #
    # lang_dirs is EVERY root this language occupies, checked as one unit the
    # way English already is (and the way the game loads them). A gated compat
    # root is not a language of its own: a compat-root trait's injections can
    # only live under 1.6/Mods/<Mod Name>/Languages/<Lang>/ (MayRequire
    # is ignored on DefInjected, so the LoadFolders gate has to be the folder),
    # yet the sidecar marks them required — checking that root standalone would
    # demand the whole Keyed set and every other def's injections from it.
    lang = lang_dirs[0].name

    # --- Keyed ---
    keyed = collect_keyed(lang_dirs, report)
    label = f"[{lang}/Keyed]"
    for key in sorted(set(english_keyed) - set(keyed)):
        report.error(label, f"missing key <{key}>")
    for key, (_, _, path) in sorted(keyed.items()):
        if key not in english_keyed:
            report.error(path, f"unknown key <{key}> (not in English)")
            continue
        text, en, _ = keyed[key]
        en_text = english_keyed[key][0]
        if isinstance(text, str) and isinstance(en_text, str):
            if placeholders(text) != placeholders(en_text):
                report.error(path, f"<{key}> placeholders {sorted(placeholders(text))} "
                                   f"!= English {sorted(placeholders(en_text))}")
        if en is None:
            report.warn(path, f"<{key}> has no EN: comment")
        elif isinstance(en_text, str) and norm(en) != norm(en_text):
            report.error(path, f"<{key}> is STALE: EN comment does not match current "
                               f"English text")

    # --- DefInjected ---
    found = {}       # def_type -> canonical keys / "<key>.<idx>" elements
    full_lists = {}  # def_type -> canonical collection keys translated as full lists
    seen = {}        # def_type -> key -> first path (dedup across every root)
    folders = []
    for lang_dir in lang_dirs:
        inj_root = lang_dir / "DefInjected"
        if inj_root.is_dir():
            folders.extend((p, lang_dir.parent.parent)
                           for p in sorted(inj_root.iterdir()) if p.is_dir())
    for folder, entry_root in folders:
        def_type = folder.name
        if def_type not in sidecar.def_types:
            report.error(folder, f"folder does not match any def type in the "
                                 f"sidecar (expected one of: "
                                 f"{', '.join(sorted(sidecar.def_types))})")
            continue
        for path in sorted(folder.glob("**/*.xml")):
            entries = load_language_xml(path, report)
            for key, elem, en in entries or []:
                by_key = seen.setdefault(def_type, {})
                if key in by_key:
                    report.error(path, f"duplicate key <{key}> (also in "
                                       f"{by_key[key]})")
                    continue
                by_key[key] = path
                resolved = sidecar.lookup(def_type, key)
                if resolved is None:
                    report.error(path, f"<{key}>: not a legal injection point "
                                       f"per the sidecar (typo, or "
                                       f"expectations stale — rerun "
                                       f"Scripts/refresh-translation-"
                                       f"expectations.py)")
                    continue
                canonical, idx = resolved
                check_entry_root(def_roots, def_type, canonical,
                                 entry_root, path, report)
                entry = sidecar.entries[def_type][canonical]
                text = flatten_entry(elem)
                if idx is not None:
                    found.setdefault(def_type, set()).add(f"{canonical}.{idx}")
                    en_text = entry["english"][idx]
                elif entry.get("isCollection"):
                    found.setdefault(def_type, set()).add(canonical)
                    full_lists.setdefault(def_type, set()).add(canonical)
                    en_text = None
                    if not isinstance(text, list):
                        report.error(path, f"<{key}> is a collection but the "
                                           f"translation is not a <li> list")
                    elif not entry.get("fullListAllowed") \
                            and len(text) != len(entry["english"]):
                        report.error(path, f"<{key}> full-list translation has "
                                           f"{len(text)} elements, English has "
                                           f"{len(entry['english'])}")
                else:
                    found.setdefault(def_type, set()).add(canonical)
                    en_text = entry["english"]
                if isinstance(text, str) and en_text is not None:
                    if placeholders(text) != placeholders(en_text):
                        report.error(path, f"<{key}> placeholders {sorted(placeholders(text))} "
                                           f"!= English {sorted(placeholders(en_text))}")
                if en is None:
                    report.warn(path, f"<{key}> has no EN: comment")
                elif en_text is not None and norm(en) != norm(en_text):
                    report.error(path, f"<{key}> is STALE: EN comment does not match "
                                       f"current English source")

    # Completeness: every required sidecar entry must be translated. A
    # required collection is satisfied by a full-list translation or by all
    # of its elements. An entire def type nobody has started translating
    # lands here too — the old per-folder walk silently skipped those (how
    # the WeaponCategoryDef labels shipped missing in all languages).
    for def_type in sorted(sidecar.def_types):
        got = found.get(def_type, set())
        for key, entry in sorted(sidecar.required(def_type).items()):
            # Defs declared in a gated compat root take their translations
            # there too — say so, or the obvious fix for the error (add the
            # key to the main tree) ships a wrong-root bug the game catches
            # only when the gate is inactive.
            owner = def_roots.get(def_type, {}).get(key.split(".")[0])
            where = f" — belongs under {owner / 'Languages' / lang}" \
                if owner is not None and owner.parent.name == "Mods" else ""
            if not entry.get("isCollection"):
                if key not in got:
                    report.error(f"[{lang}/DefInjected/{def_type}]",
                                 f"missing <{key}> (EN: "
                                 f"{entry['english']!r}){where}")
            elif key not in full_lists.get(def_type, set()):
                for i, en_text in enumerate(entry["english"]):
                    if f"{key}.{i}" not in got:
                        report.error(f"[{lang}/DefInjected/{def_type}]",
                                     f"missing <{key}.{i}> (EN: "
                                     f"{en_text!r}){where}")
    return found


def main():
    ap = argparse.ArgumentParser(description="Validate mod translation files.")
    # Default: the shim-provided REPO_ROOT (derived from the shim's own
    # location, so the checker works from any cwd, as it always has), falling
    # back to the current working directory when run without a shim. A path
    # derived from THIS file's location would be wrong: the engine lives in
    # the shared rimworld-l10n checkout, not the consuming repo.
    ap.add_argument("--root", type=Path, default=REPO_ROOT or Path.cwd(),
                    help="repo root (default: the shim's repo, else cwd)")
    ap.add_argument("--strict", action="store_true", help="treat warnings as errors")
    args = ap.parse_args()

    if REQUIRED_DLCS is None:
        sys.exit("check_translations engine misconfigured: REQUIRED_DLCS is "
                 "None — the consuming repo's Scripts/check-translations.py "
                 "shim must assign it after importing this engine (an empty "
                 "set() is a legitimate 'no DLC required' value; None means "
                 "the shim never set it)")

    # */Mods/*/Languages picks up gated compat load roots, which nest inside the
    # version folder as <version>/Mods/<Mod Name>/ (see LoadFolders.xml).
    lang_roots = sorted(args.root.glob("*/Languages")) + \
                 sorted(args.root.glob("*/Mods/*/Languages")) + \
                 ([args.root / "Languages"] if (args.root / "Languages").is_dir() else [])
    defs_dirs = sorted(args.root.glob("*/Defs")) + \
                sorted(args.root.glob("*/Mods/*/Defs")) + \
                ([args.root / "Defs"] if (args.root / "Defs").is_dir() else [])
    if not lang_roots:
        if ALLOW_NO_KEYED_SURFACE:
            print(f"note: no Languages/ directory under {args.root} — no "
                  "translations shipped yet; checking sidecar freshness only.")
        else:
            print(f"No Languages/ directory found under {args.root}", file=sys.stderr)
            return 2

    report = Report()
    sidecar = load_sidecar(args.root, report)
    if sidecar is None:
        return 2
    defs, def_roots = collect_defs(defs_dirs, sidecar.active_packages)
    check_sidecar_freshness(defs, sidecar, report)

    # A language is the union of its dirs across every root, not one dir per
    # root — see check_language. English already worked this way; the rest now
    # do too, so a gated compat root can hold the injections that may only live
    # there without being mistaken for a half-empty language of its own.
    english_dirs = []
    languages = {}   # language name -> [dirs], in load order
    english_injected_seen = {}
    for lang_root in lang_roots:
        for lang_dir in sorted(p for p in lang_root.iterdir() if p.is_dir()):
            if lang_dir.name == "English":
                english_dirs.append(lang_dir)
                check_english_definjected(lang_dir, sidecar, def_roots,
                                          english_injected_seen, report)
            else:
                languages.setdefault(lang_dir.name, []).append(lang_dir)
    english_keyed = collect_keyed(english_dirs, report)

    if not english_keyed:
        if ALLOW_NO_KEYED_SURFACE:
            print("note: no English Keyed strings — this mod has no Keyed "
                  "surface; DefInjected checks run against the sidecar alone.")
        else:
            print("No English Keyed strings found; nothing to check against.", file=sys.stderr)
            return 2

    found_by_lang = {}
    for lang, lang_dirs in sorted(languages.items()):
        found_by_lang[lang] = check_language(
            lang_dirs, english_keyed, sidecar, def_roots, report)

    # Cross-language parity: any DefInjected key one language translates
    # beyond the required set (secondary fields, extra collection elements)
    # must exist in every language — a key added in one pass and forgotten in
    # the others is exactly the drift this catches. Keys compare in
    # canonical (sidecar) spelling, so index-form and handle-form
    # translations of the same field cannot false-positive.
    union = {}
    for found in found_by_lang.values():
        for def_type, keys in found.items():
            union.setdefault(def_type, set()).update(keys)
    demanded = {}  # def_type -> required keys expanded to element form
    for def_type in sidecar.def_types:
        dem = demanded.setdefault(def_type, set())
        for key, entry in sidecar.required(def_type).items():
            dem.add(key)
            if entry.get("isCollection"):
                dem.update(f"{key}.{i}" for i in range(len(entry["english"])))
    for lang, found in sorted(found_by_lang.items()):
        for def_type, keys in sorted(union.items()):
            extra = keys - found.get(def_type, set()) \
                - demanded.get(def_type, set())
            extra = {k for k in extra
                     if not ({k.split(".")[-1], k.split(".")[-2] if
                              k.split(".")[-1].isdigit() else None}
                             & PARITY_EXEMPT_FIELDS)}
            for key in sorted(extra):
                report.error(f"[{lang}/DefInjected/{def_type}]",
                             f"missing <{key}> (translated in other languages)")

    for line in report.errors:
        print(f"ERROR   {line}")
    for line in report.warnings:
        print(f"WARNING {line}")
    checked = ", ".join(sorted(languages)) or "none"
    print(f"\n{len(english_keyed)} English keys; languages checked: {checked}")
    print(f"{len(report.errors)} error(s), {len(report.warnings)} warning(s)")
    return 1 if report.errors or (args.strict and report.warnings) else 0


if __name__ == "__main__":
    sys.exit(main())
